class Emoji:
    SANTA = "🎅"
    PRESENT = "🎁"
    TREE = "🎄"
    SNOW = "❄️"
    SNOWMAN = "⛄️"
    SNOWMAN_2 = "☃️"
    FREEZE = "🥶"
    CROSS = "❌"
    HOURGLASS = "⏳"
    WARN = "⚠️"
    SHH = "🤫"
    LIST = "📜"
    SAD = "😔"
